spring:
  datasource:
    #    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:tc:mariadb://localhost:3306/my_db
    username: user
    password: user
  #  flyway:
  #    url: jdbc:tc:mariadb://localhost:3306/my_db
  #    user: user
  #    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
